### ISSUE TITLE
ECONNRESET after a while

### ISSUE THREAD

**Issue by royibernthal** [pagerinc/jackrabbit#334]
I keep getting the ECONNRESET error after a while. Any idea what might be the cause?

I'm using jackrabbit along with CloudAMQP.

```
Error: write ECONNRESET
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:784:11)
    at Socket._write (net.js:796:8)
    at doWrite (_stream_writable.js:442:12)
    at writeOrBuffer (_stream_writable.js:426:5)
    at Socket.Writable.write (_stream_writable.js:317:11)
    at Connection.C.sendBytes (D:\Projects\microServices\services\users\node_modules\amqplib\lib\connection.js:519:15)
    at Connection.C.sendHeartbeat (D:\Projects\microServices\services\users\node_modules\amqplib\lib\connection.js:523:15)
    at Heart.<anonymous> (D:\Projects\microServices\services\users\node_modules\amqplib\lib\connection.js:433:12)
    at Heart.emit (events.js:310:20)
    at Heart.EventEmitter.emit (domain.js:482:12)
    at Heart.runHeartbeat (D:\Projects\microServices\services\users\node_modules\amqplib\lib\heartbeat.js:88:17)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by DiegoRBaquero** [comment]
Hi @royibernthal, seems the connection is being reset from CloudAMQP, does this happen after a fixed amount of time?

**Comment by royibernthal** [comment]
Hi @DiegoRBaquero, it's hard to tell if it happens after a fixed amount of time, but my guess would be yes.

Can there be a different reason for this issue or are you sure that the connection is being reset from CloudAMQP?

**Comment by Filaind** [comment]
Have same problem on Amazon MQ
I think we need implement reconnection
