### ISSUE TITLE
unhandled "Unexpected close"

### ISSUE THREAD

**Issue by erSitzt** [pagerinc/jackrabbit#882]
Hi,

im getting an unexpected close error and jackrabbit does not reconnect...

I'm not sure where the disconnect is happening right now, but i thought jackrabbit would handle disconnects/reconnects ?
```
node:events:371
      throw er; // Unhandled 'error' event
      ^
Error: Unexpected close
    at succeed (/usr/src/app/node_modules/@pager/jackrabbit/node_modules/amqplib/lib/connection.js:272:13)
    at onOpenOk (/usr/src/app/node_modules/@pager/jackrabbit/node_modules/amqplib/lib/connection.js:254:5)
    at /usr/src/app/node_modules/@pager/jackrabbit/node_modules/amqplib/lib/connection.js:166:32
    at /usr/src/app/node_modules/@pager/jackrabbit/node_modules/amqplib/lib/connection.js:160:12
    at Socket.recv (/usr/src/app/node_modules/@pager/jackrabbit/node_modules/amqplib/lib/connection.js:499:12)
    at Object.onceWrapper (node:events:513:28)
    at Socket.emit (node:events:394:28)
    at emitReadable_ (node:internal/streams/readable:571:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on CallbackModel instance at:
    at Connection.emit (node:events:394:28)
    at Connection.C.onSocketError (/usr/src/app/node_modules/@pager/jackrabbit/node_modules/amqplib/lib/connection.js:353:10)
    at Socket.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1329:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by erSitzt** [comment]
Closing the connection from RabbitMQs Management does result in a reconnect though...
